name: PR Checks Demo

on:
  pull_request:
    branches: 
      - main
    paths:
      - pr-checks-demo.md

jobs:
  do-work:
    name: Do Some CI Work
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 10
          echo "Working hard..."
          echo "..and still failing."
          exit 1
          
